import os
import json
import datetime
from core.base_agent import BaseAgent
from core.config import REPORTS_PATH


class ReportAgent(BaseAgent):
    """
    Report Agent — generates the final security report.

    Outputs:
    - JSON report
    - Markdown report

    Reports are generated only for authorized security testing.
    CVE identifiers are not invented. If a vulnerability does not
    have a verified CVE, the report states:
    "Not assigned / Not applicable".

    Severity values are reported as AGELA Severity Scores unless
    a formal CVSS calculation has been implemented.
    """

    def __init__(self, model: str = "mistral"):
        super().__init__(name="ReportAgent", model=model)
        os.makedirs(REPORTS_PATH, exist_ok=True)

    def run(self, context: dict) -> dict:
        self.log("Generating security report")

        pipeline_id = context.get("pipeline_id", "unknown")
        target_url = context.get("target_url", "unknown")
        validated = context.get("validated", [])
        tech_stack = context.get("recon", {}).get("tech_stack", {})
        summary = context.get(
            "validation_summary",
            "No vulnerabilities found."
        )

        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        report_name = f"AGELA_Report_{timestamp}"

        # ---------------------------------------------------------
        # Ask LLM to write executive summary
        # ---------------------------------------------------------
        system_prompt = """You are a professional cybersecurity report writer.

Write clear, factual, professional security assessment reports.

Important rules:
1. Do NOT invent CVE identifiers.
2. Do NOT create fake CVE numbers such as CVE-20XX-XXXX.
3. Do NOT claim that a vulnerability has an official CVSS score unless
   the supplied data explicitly provides a verified CVSS assessment.
4. AGELA's configured severity values should be described as
   "AGELA Severity Scores".
5. Base the report only on the supplied assessment results.
6. Do not claim exploitation beyond the evidence provided.
"""

        severity_breakdown = {
            s: sum(
                1
                for v in validated
                if v.get("severity") == s
            )
            for s in ["Critical", "High", "Medium", "Low"]
        }

        prompt = f"""
Write a professional executive summary for this security assessment.

Target:
{target_url}

Tech Stack:
{tech_stack}

Vulnerabilities Found:
{len(validated)}

Severity Breakdown:
{severity_breakdown}

Vulnerability Details:
{validated}

Write:

1. Executive Summary
   - 3-4 sentences
   - Clearly state what was found.
   - Do not invent vulnerability identifiers.

2. Risk Assessment
   - 1-2 sentences.
   - Explain the potential security impact based only on the evidence.

3. Immediate Actions Required
   - Bullet points.
   - Provide practical remediation recommendations.

Important:
- Do not mention any fake CVE number.
- Do not create a CVE identifier.
- Do not call AGELA's severity values official CVSS scores.
- Refer to the supplied severity values as AGELA Severity Scores.
"""

        executive_summary = self.think(prompt, system_prompt)

        # ---------------------------------------------------------
        # Build report
        # ---------------------------------------------------------
        report = {
            "report_id": report_name,
            "pipeline_id": pipeline_id,
            "generated_at": datetime.datetime.now().isoformat(),
            "target": target_url,
            "tech_stack": tech_stack,
            "total_vulns": len(validated),
            "severity_breakdown": severity_breakdown,
            "executive_summary": executive_summary,
            "vulnerabilities": validated,
            "validation_summary": summary,
            "tool": "AGELA v1.0",
            "severity_method": (
                "AGELA Severity Score. "
                "These values are configured by the AGELA framework "
                "and are not official CVSS calculations."
            ),
            "disclaimer": (
                "This report was generated by AGELA under authorized "
                "security testing conditions only."
            )
        }

        # ---------------------------------------------------------
        # Save JSON report
        # ---------------------------------------------------------
        json_path = os.path.join(
            REPORTS_PATH,
            f"{report_name}.json"
        )

        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2)

        self.log(f"JSON report saved: {json_path}")

        # ---------------------------------------------------------
        # Save Markdown report
        # ---------------------------------------------------------
        md_path = os.path.join(
            REPORTS_PATH,
            f"{report_name}.md"
        )

        with open(md_path, "w", encoding="utf-8") as f:
            f.write(self._build_markdown(report))

        self.log(f"Markdown report saved: {md_path}")

        # ---------------------------------------------------------
        # Add report information to pipeline context
        # ---------------------------------------------------------
        context["report"] = {
            "file": json_path,
            "markdown_file": md_path,
            "total_vulns": len(validated),
            "severity_breakdown": report["severity_breakdown"],
            "executive_summary": executive_summary
        }

        return context

    def _build_markdown(self, report: dict) -> str:
        """
        Build the Markdown version of the security report.
        """

        lines = [
            "# AGELA Security Report",
            "",
            f"**Report ID:** {report['report_id']}",
            f"**Target:** {report['target']}",
            f"**Generated:** {report['generated_at']}",
            f"**Tool:** {report['tool']}",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            report["executive_summary"],
            "",
            "---",
            "",
            "## Severity Breakdown",
            "",
            "| Severity | Count |",
            "|----------|-------|",
        ]

        # Add severity counts
        for sev, count in report["severity_breakdown"].items():
            lines.append(f"| {sev} | {count} |")

        lines += [
            "",
            "---",
            "",
            "## Severity Method",
            "",
            report["severity_method"],
            "",
            "---",
            "",
            "## Confirmed Vulnerabilities",
            ""
        ]

        # ---------------------------------------------------------
        # Add vulnerability details
        # ---------------------------------------------------------
        for i, vuln in enumerate(report["vulnerabilities"], 1):

            attack_type = vuln.get(
                "attack_type",
                "Unknown"
            )

            severity = vuln.get(
                "severity",
                "Unknown"
            )

            url = vuln.get(
                "url",
                "Unknown"
            )

            payload = vuln.get(
                "payload",
                "Not provided"
            )

            evidence = vuln.get(
                "evidence",
                "No evidence provided"
            )

            # Use the existing AGELA score field.
            # Older validation results may call this cvss_score,
            # so we preserve compatibility while changing the
            # report label to AGELA Severity Score.
            agela_score = vuln.get(
                "agela_severity_score",
                vuln.get("cvss_score", "Not provided")
            )

            # Optional successful payload information
            successful_payloads = vuln.get(
                "successful_payloads",
                []
            )

            successful_payload_count = vuln.get(
                "successful_payload_count",
                len(successful_payloads)
            )

            lines += [
                f"### {i}. {attack_type} [{severity}]",
                "",
                f"- **URL:** {url}",
                f"- **Payload:** `{payload}`",
                "- **CVE:** Not assigned / Not applicable",
                f"- **AGELA Severity Score:** {agela_score}",
                f"- **Evidence:** {evidence}",
            ]

            # Add successful payload count when available
            if successful_payload_count:
                lines.append(
                    f"- **Successful Payload Count:** "
                    f"{successful_payload_count}"
                )

            # Add all successful payloads when available
            if successful_payloads:
                lines += [
                    "",
                    "**Successful Payloads:**",
                    ""
                ]

                for successful_payload in successful_payloads:
                    lines.append(
                        f"- `{successful_payload}`"
                    )

            lines.append("")

        # ---------------------------------------------------------
        # Footer
        # ---------------------------------------------------------
        lines += [
            "---",
            "",
            f"*{report['disclaimer']}*"
        ]

        return "\n".join(lines)